[project]
name = "Solar-Panel-AI-Analysis"
version = "0.1.0"
description = "Multi-Modal (RGB & Thermal) Solar Panel Object Detection System YOLO-based object detection pipeline for identifying and classifying specific defects in solar panels using both RGB and thermal imagery. Includes preprocessing, custom labeling workflows, and Dockerized deployment"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "albumentations>=2.0.8",
    "label-studio>=1.22.0",
    "opencv-python>=4.13.0.92",
    "reportlab>=4.4.10",
    "structlog>=25.5.0",
    "ultralytics>=8.3.0",
    "onnxruntime-gpu>=1.20",
    "onnxslim>=0.1.34",
    "onnx>=1.12.0,<2.0.0",
    "torch",
    "torchvision",
    "pyqt6>=6.11.0",
    "tensorrt-cu12>=10.0",
    "tensorrt-cu12-bindings>=10.0",
    "tensorrt-cu12-libs>=10.0",
]

[tool.uv.sources]
torch = { index = "pytorch-cu124" }
torchvision = { index = "pytorch-cu124" }
tensorrt-cu12 = { index = "nvidia" }
tensorrt-cu12-bindings = { index = "nvidia" }
tensorrt-cu12-libs = { index = "nvidia" }

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[[tool.uv.index]]
name = "nvidia"
url = "https://pypi.nvidia.com"
explicit = true
