path: data/processed_data/solar/unified_dataset
train: train/images
val: val/images
test: test/images

nc: 6
names:
  0: bird_drop
  1: bird_feather
  2: physical_damage
  3: dust_particle
  4: leaf
  5: snow

# Yeni birlestirilmis ve cogaltilmis dataset notlari
modality: unified
version: unified_v2
notes: "Format 1 (OBB) ve Format 2 (HBB) birlestirildi. Tüy, Damla ve Fiziksel hasar asırı coklandı. Healthy iptal."
